language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: CUDA 8
      env:
      - CUDA=8.0.61-1
      - CUDA_SHORT=8.0
      - UBUNTU_VERSION=ubuntu1604
      dist: xenial
    - name: CUDA 9
      env:
      - CUDA=9.2.148-1
      - CUDA_SHORT=9.2
      - UBUNTU_VERSION=ubuntu1604
      dist: xenial
    - name: CUDA 10
      env:
      - CUDA=10.1.105-1
      - CUDA_SHORT=10.1
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
  - sudo apt update
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt update
  - sudo apt install -y python3-pip python3.6
  - pip3.6 install -U pip
  - pip3.6 install -r requirements.txt
  - python3.6 -m grpc_tools.protoc --python_out cusim/ --proto_path cusim/proto/ config.proto
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - PATH=${PATH}:${PWD}

script:
  - python3.6 setup.py install
